# Generated by Django 5.0.1 on 2024-02-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
