# Generated by Django 5.0.1 on 2024-02-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0005_user_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('likes', models.CharField(max_length=20)),
                ('dislikes', models.CharField(max_length=20)),
                ('aboutme', models.TextField(max_length=255)),
            ],
        ),
    ]
