# Generated by Django 5.0.1 on 2024-02-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0007_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userid',
            field=models.CharField(default='rain', max_length=20),
        ),
    ]
