# Generated by Django 5.0.1 on 2024-02-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0008_profile_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField(max_length=2000)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女'), ('不顯示', '不顯示')], max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(max_length=20),
        ),
    ]
