# Generated by Django 5.0.1 on 2024-02-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0009_article_alter_profile_gender_alter_profile_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='userid',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='userid',
            new_name='username',
        ),
    ]
