# Generated by Django 5.0.1 on 2024-02-06 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0010_rename_userid_article_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albummodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Photomodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psubject', models.CharField(max_length=100)),
                ('purl', models.CharField(max_length=100)),
                ('palbum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudpractice.albummodel')),
            ],
        ),
    ]
