# Generated by Django 5.0.1 on 2024-02-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0011_albummodel_photomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='albummodel',
            name='adesc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
