# Generated by Django 5.0.1 on 2024-02-06 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0012_albummodel_adesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profilepicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='profile_pics/')),
                ('puser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudpractice.profile')),
            ],
        ),
    ]
