# Generated by Django 5.0.1 on 2024-02-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0013_profilepicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profilepicture',
        ),
    ]
