# Generated by Django 5.0.1 on 2024-02-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0014_delete_profilepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profilepicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile/')),
            ],
        ),
    ]
