# Generated by Django 5.0.1 on 2024-02-10 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0016_myimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimagemodel',
            name='album',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crudpractice.albummodel'),
            preserve_default=False,
        ),
    ]
