# Generated by Django 5.0.1 on 2024-02-10 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0017_myimagemodel_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myimagemodel',
            name='album',
        ),
    ]
