# Generated by Django 5.0.1 on 2024-02-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0018_remove_myimagemodel_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyImageModel',
        ),
    ]
