# Generated by Django 5.0.1 on 2024-02-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0020_myimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimagemodel',
            name='imagedesc',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
