# Generated by Django 5.0.1 on 2024-02-15 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0021_myimagemodel_imagedesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomodel',
            name='palbum',
        ),
        migrations.DeleteModel(
            name='Profilepicture',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crudpractice.user'),
        ),
        migrations.AlterField(
            model_name='myimagemodel',
            name='imagedesc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Photomodel',
        ),
    ]
