# Generated by Django 5.0.1 on 2024-02-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0022_remove_photomodel_palbum_delete_profilepicture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
