# Generated by Django 5.0.1 on 2024-02-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0024_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='datestart',
        ),
    ]
