# Generated by Django 5.0.1 on 2024-02-16 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0026_article_datelast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='datelast',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 7, 46, 35, 831440, tzinfo=datetime.timezone.utc)),
        ),
    ]
