# Generated by Django 5.0.1 on 2024-02-16 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0027_alter_article_datelast'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(default='profilepic/rain.jpg', upload_to='profilepic/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='datelast',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 8, 0, 40, 567985, tzinfo=datetime.timezone.utc)),
        ),
    ]
