# Generated by Django 5.0.1 on 2024-02-16 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0028_profile_profilepic_alter_article_datelast'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyImageModel',
            new_name='PhotoModel',
        ),
        migrations.AlterField(
            model_name='article',
            name='datelast',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 17, 24, 28, 744230, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(upload_to='profilepic/'),
        ),
    ]
