# Generated by Django 5.0.1 on 2024-02-17 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0030_alter_article_datelast'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=2000)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='datelast',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 6, 27, 30, 995850, tzinfo=datetime.timezone.utc)),
        ),
    ]
