# Generated by Django 5.0.1 on 2024-02-17 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0031_boardmodel_alter_article_datelast'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='useremail',
            field=models.EmailField(default='jojoj@mail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='useruser',
            field=models.CharField(default='john', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='datelast',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 7, 28, 48, 362349, tzinfo=datetime.timezone.utc)),
        ),
    ]
