# Generated by Django 5.0.1 on 2024-02-19 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0032_boardmodel_useremail_boardmodel_useruser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='datelast',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 6, 51, 56, 957620, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='useremail',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='useruser',
            field=models.CharField(max_length=20),
        ),
    ]
