# Generated by Django 5.0.1 on 2024-02-19 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpractice', '0033_alter_article_datelast_alter_boardmodel_useremail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='datelast',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 6, 59, 9, 406710, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='imagedesc',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
